spring:
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  allowed:
    origins:
      - https://localhost:3000
      - http://localhost:3000
  datasource:
    url: jdbc:postgresql://localhost:5432/license
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    ignored:
      - "*.bundle.*"
    user:
      name: admin
      password: password
      roles: USER,ADMIN

file:
  upload-dir: D:\Repos\licenta\videos
  results-dir: D:\Repos\licenta\results

license:
  app:
    jwtSecret: LicenseSecret
    jwtExpirationMs: 8400000
server:
  tomcat:
    max-swallow-size: 200MB

scripts:
  api: http://localhost:5000/api/
